name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:  [ ubuntu-latest ]
        java: [1.8, 8, 11, 17]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Java code
        run: javac Driver.java

      - name: Test Java application
        run: java Driver > output.txt

      - name: Validate JFrame opened
        run: |
          if grep -q 'Compiled Su' output.txt; then
            echo "JFrame opened successfully"
          else
            echo "JFrame not opened"
            exit 2
          fi

