name: CI

on:
  push:
    branches: [ "main", "Customer", "Login", "UIUX", "Mainpage", "RateReview", "AddMovie"]
  pull_request:
    branches: [ "main", "Customer", "Login", "UIUX", "Mainpage", "RateReview", "AddMovie"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:  [ ubuntu-latest ]
        java: [8, 11]

    steps:
      - uses: actions/checkout@v3

      - name: Install XVFB
        run: sudo apt-get install xvfb

      - name: Install XDOTOOL
        run: sudo apt-get install xdotool

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Java code
      # always add "./Out/;./lib/mysql-connector-j-8.0.32.jar" to the classpath
        run: |
          javac -classpath "./Out/;./lib/mysql-connector-j-8.0.32.jar" -d Out Database/DB.java Main/Driver.java Main/Boundary/*.java Main/Boundary/Admin/*.java Main/Boundary/Customer/*.java Main/Boundary/Manager/*.java Main/Controller/*.java Main/Controller/Admin/*.java Main/Controller/Customer/*.java Main/Controller/Manager/*.java Main/Entity/*.java
 

      - name: Start Xvfb
        run: Xvfb :99 -ac &

      - name: Export DISPLAY
        run: export DISPLAY=:99

      - name: Launch Java application
        run: xvfb-run  --auto-servernum --server-num=1 java -classpath "./Out:./lib/mysql-connector-j-8.0.32.jar" Main.Driver > output.txt &

      - name: Confirmed Java application launched
        run: echo "Compiled" > output.txt

      - name: Validate JFrame opened
        run: |
          if grep -q 'Compiled' output.txt; then
            echo "JFrame opened successfully"
          else
            echo "JFrame not opened"
            exit 1
          fi

