name: MySQL DB CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: booking
          MYSQL_PASSWORD: jG9GfE6XkNF5BYKJJfe8
        ports:
          - 25060:25060
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for MySQL to start
        run: |
          until docker exec mysql mysql -ubooking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -e "SELECT 1"; do
            sleep 1;
          done

      - name: Insert test data
        uses: mysql/mysql-docker@master
        with:
          args: mysql -u booking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE Test; INSERT INTO users VALUES (1, 'Alice'); INSERT INTO users VALUES (2, 'Bob')"

      - name: Delete test data
        uses: mysql/mysql-docker@master
        with:
          args: mysql -u booking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE test; DELETE FROM users"
