name: MySQL CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up MySQL
      uses: mysql-actions/setup-mysql@v1
      with:
        mysql-version: '8.0'
        mysql-host: 'csit314-project-do-user-13025854-0.b.db.ondigitalocean.com'
        mysql-port: '25060 '
        mysql-user: 'booking'
        mysql-password: ${{ secrets.MYSQL_PASSWORD }}
    
    - name: Insert test data
      run: |
        mysql -h  mysql -u booking -p${{ secrets.MYSQL_PASSWORD }} -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE Test; INSERT INTO users VALUES (1, 'Alice'); INSERT INTO users VALUES (2, 'Bob')"
    
    - name: Delete test data
      run: |
        mysql -u booking -p${{ secrets.MYSQL_PASSWORD }} -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE test; DELETE FROM users"
