name: MySQL DB CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL service
        uses: docker/compose-action@1.0.0
        with:
          compose-file: docker-compose.yml
          service: mysql
          command: up -d

      - name: Wait for MySQL to start
        run: |
          until docker exec mysql mysql -ubooking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -e "SELECT 1"; do
            sleep 1;
          done

      - name: Insert test data
        uses: docker://mysql:latest
        with:
          args: mysql -u booking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE Test; INSERT INTO users VALUES (1, 'Alice'); INSERT INTO users VALUES (2, 'Bob')"

      - name: Delete test data
        uses: docker://mysql:latest
        with:
          args: mysql -u booking -pjG9GfE6XkNF5BYKJJfe8 -h csit314-project-do-user-13025854-0.b.db.ondigitalocean.com -P 25060 -D Test -e "USE test; DELETE FROM users"
